### PR TITLE
Adding audio settings menu

### PR DESCRIPTION
**Pull request by chase-cobb**
Added EEasyXB submodule and created an audio settings menu that implements the new submodule. The menu allows users to change their desired audio settings in the Xbox eeprom. 

Also made some changes in menu h/cpp to allow dynamic text in menu items. This is useful for items that can be toggled or need to present the user with text that may change with configuration.

### CODE REVIEW

**Comment by chase-cobb** [comment]
This still needs cleanup and I'm hoping for some feedback.

**Comment by chase-cobb** [comment]
Refactored EEasyXB to allow AC3 and DTS in stereo mode. Updated the EEasyXB submodule and modified audio settings to reflect the changes.

**Comment by dracc** [comment]
Thank you for your nice PR.
I feel it's a bit much with a full submodule for what is essentially two bytes in the EEPROM.
I also already had this work laying around waiting for the finishing touches before upload.

I'm sorry I was so blunt in how this got closed, I should have communicated better.

**Comment by chase-cobb** [comment]
We definitely differ in our approaches. Good luck to you with this and all other future projects.

**Pull request closed without merging**
